http://localhost:3000/

###

http://localhost:3000/users



###

http://localhost:3000/recipes/684f32d431875c50de2e4494

###
POST http://localhost:3000/recipes
Content-Type: application/json

{
  "title": "Indian Chicken Curry",
  "ingredients": [
    "chicken",
    "onion",
    "tomato",
    "curry powder",
    "yogurt"
  ],
  "instructions": "Sauté onions and tomatoes. Add chicken and curry powder. Simmer with yogurt until cooked.",
  "cookingTime": 40,
  "difficulty": "Medium",
  "tags": [
    "indian",
    "spicy"
  ],
  "imageUrl": "https://example.com/curry.jpg",
  "createdBy": "user789"
}
###

PUT http://localhost:3000/recipes/684f3d073851fec4b131e5ca
Content-Type: application/json

{
  "title": "Chicken Curry",
  "ingredients": [
    "chicken",
    "onion",
    "tomatoes",
    "curry powder",
    "yogurt"
  ],
  "instructions": "Sauté onions and tomatoes. Add chicken and curry powder. Simmer with yogurt until cooked.",
  "cookingTime": 40,
  "difficulty": "Medium",
  "tags": [
    "indian",
    "spicy"
  ],
  "imageUrl": "https://example.com/curry.jpg",
  "createdBy": "user789"
}

###

DELETE http://localhost:3000/recipes/684f3d073851fec4b131e5ca